export const FINANCIALS = {
  SHOW_UPLOAD_PDF: "SHOW_UPLOAD_PDF",
  UPLOAD_FILE_TO_S3: "UPLOAD_FILE_TO_S3",
  UPLOAD_FILE_TO_S3_SUCCESS: "UPLOAD_FILE_TO_S3_SUCCESS",
  UPLOAD_FILE_TO_S3_FAILURE: "UPLOAD_FILE_TO_S3_FAILURE",

  GET_SCHEDULE_PAGES: "GET_SCHEDULE_PAGES",
  GET_SCHEDULE_PAGES_SUCCESS: "GET_SCHEDULE_PAGES_SUCCESS",
  GET_SCHEDULE_PAGES_FAILURE: "GET_SCHEDULE_PAGES_FAILURE",

  GET_SCHEDULE_PAGES_COMPLETED: "GET_SCHEDULE_PAGES_COMPLETED",
  SET_ACTIVE_PAGE: "SET_ACTIVE_PAGE",
  SET_TOTALPAGES_OF_PDF: "SET_TOTALPAGES_OF_PDF",
  SET_DISABLE_EXTRACT_BTN: "SET_DISABLE_EXTRACT_BTN",
  SHOW_OUTPUT_SCREEN: "SET_SHOW_OUTPUT_SCREEN",

  SET_ACTIVE_BOND: "SET_ACTIVE_BOND",
  RESET_PDF_SELECTION: "RESET_PDF_SELECTION",

  EXTRACT_FINANCIAL_FROM_ALEXANDRIA: "EXTRACT_FINANCIAL_FROM_ALEXANDRIA",

  IS_EXTRACTION_DATA_SUCCESS: "IS_EXTRACTION_DATA_SUCCESS",
  BS_EXTRACTION_DATA_SUCCESS: "BS_EXTRACTION_DATA_SUCCESS",
  CF_EXTRACTION_DATA_SUCCESS: "CF_EXTRACTION_DATA_SUCCESS",

  IS_EXTRACTION_DATA_FAILURE: "IS_EXTRACTION_DATA_FAILURE",
  BS_EXTRACTION_DATA_FAILURE: "BS_EXTRACTION_DATA_FAILURE",
  CF_EXTRACTION_DATA_FAILURE: "CF_EXTRACTION_DATA_FAILURE",

  EXTRACT_FINANCIAL_FROM_ALEXANDRIA_CF: "EXTRACT_FINANCIAL_FROM_ALEXANDRIA_CF",
  EXTRACT_FINANCIAL_FROM_ALEXANDRIA_BS: "EXTRACT_FINANCIAL_FROM_ALEXANDRIA_BS",
  EXTRACT_FINANCIAL_FROM_ALEXANDRIA_IS: "EXTRACT_FINANCIAL_FROM_ALEXANDRIA_IS",
};

export const MESSAGES = {
  INVALID_INPUT: "Invalid input type",
  DUPLICATE_PAGE_NUMBER: "Duplicate page numbers not allowed",
  PAGE_NUMBER_BETWEEN:
    "Only page numbers between <FIRST> and <LAST> are allowed",
  SELECT_DATE_BEFORE_CURRENT: "Date can not be greater than today's date",
};

export const GROUPS = {
  CREATE_GROUPS: "CREATE_GROUPS",
  GROUPS_SET_STATE: "GROUPS_SET_STATE",
  GROUPS_PRESET_SAVE: "GROUPS_PRESET_SAVE",
};

export const FORMULAE = {
  FORMULAE_SET_STATE: "FORMULAE_SET_STATE",
};
