version: 0.0
os: linux
files:
  - source: /UI/Financials/
    destination: /beat-deployments/munibonds/Financials/pod/uiTemp
file_exists_behavior: OVERWRITE 
hooks:
  ApplicationStop:
    - location: UI/Financials/deployment_script/Linux/application_stop.sh 
      timeout: 300
      runas: root
  BeforeInstall:
    - location: UI/Financials/deployment_script/Linux/before_install.sh 
      timeout: 300
      runas: root
  AfterInstall:
    - location: UI/Financials/deployment_script/Linux/after_install.sh 
      timeout: 300
      runas: root
  ApplicationStart:
    - location: UI/Financials/deployment_script/Linux/application_start.sh 
      timeout: 300
      runas: root
  ValidateService:
    - location: UI/Financials/deployment_script/Linux/validate_service.sh 
      timeout: 300
      runas: root
